CREATE TABLE department (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30)
);

CREATE TABLE roles (
   id INTEGER AUTO_INCREMENT PRIMARY KEY,
   title VARCHAR(30),
   salary DECIMAL
   department_id INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE employees (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(30),
    last_name VARCHAR(30),
    role_id INTEGER AUTO_INCREMENT PRIMARY KEY,
    manager_id INTEGER AUTO_INCREMENT PRIMARY KEY,
)